### ISSUE TITLE
compile_commands.json includes files in bazel-out rather than in the source tree

### ISSUE THREAD

**Issue by johngkhs** [hedronvision/bazel-compile-commands-extractor#102]
Hi all. Let me know if I'm misunderstanding something, but shouldn't the generated compile_commands.json use header paths in the src directory (i.e. "-I src/..") rather than in bazel-out (i.e. -I bazel-out/../src/..) when possible? When going to definition in a file, or when searching for references, the files in bazel-build are pulled up which is undesirable when I'd prefer to jump to files in the actual source tree. Thank you.

**Comment by cpsauer** [comment]
Hey, John! Thanks for your interest and keen eye.

The background that's in my head: Bazel definitely does need to add header search paths for bazel-out so generated code can be included. We'll pick up those include paths when Bazel adds them--as part of getting the command bazel would execute. Bazel is relatively liberal about adding these paths--adding one, e.g., for every external directory, just in case there's generated code, as I recall.

We definitely don't want, though, to be pointing clangd to the wrong path for headers, either in navigation or in analysis. Just to confirm: These definitions you're clicking into: They're definitely not supposed to be in generated files, right? That is, there's both an undesirable generated file that's currently being brought up and a file by the same name in the source tree. If so, could you tell me what OS you're on and maybe even cook me a mini example? (I was trying to reproduce quickly on my laptop, but didn't succeed in finding the problem.)

Thanks,
Chris

**Comment by johngkhs** [comment]
Got it thank you, that does make sense and it is expected to include files in bazel-out for generated code. I think the ones I am referring to are the "virtual includes", which mirror the regular real include files in our project (I don't believe we are doing anything special on this front but not 100% sure on that). I can't share the code but I can try to cook up a mini example soon, and I am on Ubuntu. An example path in my compile_commands.json would be "-Ibazel-out/k8-fastbuild/bin/src/cpp/some_math_functions/_virtual_includes/some_math_functions_headers", which I would probably just want to resolve to -"Isrc/cpp".

**Comment by johngkhs** [comment]
I think I found what my problem is, though still not sure what the best way to resolve it is besides an automated search and replace. All my includes start from within the project_root/src directory. In each of my compile commands the first include is:
"-iquote",
 ".",

However, the "directory" in each compile command points to project_root where my WORKSPACE is, rather than project_root/src. All my include paths originate from project_root/src, so two options for me are to search and replace "." -> "src", or change the "directory" to reference "src".

I'm not sure where or how "directory" gets set. We may be doing something special there or there may be a more correct way to determine it.

**Comment by cpsauer** [comment]
Oh! Virtual includes!

These are coming from an include_prefix (or strip_include_prefix or similar), yeah? Not terribly unusual, though a nested srcs/include_prefix on first party code is a little uncommon for Bazel setups. Our repos have these for some third party code we've brought in.

At least on my machine, I'm seeing that the virtual include files are actually symlinks back to the originals. Is that what you're seeing? That is, if you edit the file, does the original still change correctly? If so, might that be okay, since you're still opening /editing the original file, albeit under the path it's being found at while compiling[preprocessing]. (I'd recommend that over the search and replace, but there might be an easier workaround you don't like going through the symlinks. More on those below.)

---
More detail to answer your other questions

The "directory" is coming from the root of your Bazel workspace. It's being set that way because all bazel compile commands are indeed being run from (a sandbox mirroring) the workspace root, with that directory indeed being among those used for header search.

The problem with the find and replace is that then the command used for analysis no longer really matches the one bazel is running, in ways that are going to start creating discrepancies in behavior. For example, if you change the directory, clangd will probably have trouble finding external workspace paths through //external, since it's one level up, or, more generally, any headers you might reference from the workspace root. Changing . would cause the latter problem for first party code, though you may well have no such headers. But if they're working symlinks to the original, then I'm guessing this'll be more long run pain than it solves, doubly if we put it in the mainline.

If the virtual includes are coming from an include_prefix, then there isn't actually a workspace path one could create an iquote for that would be valid, since there's presumably no actual workspace directory with that prefix (hence why it's being added). But if the virtual includes in your project are coming from a `strip_include_prefix="srcs"` without an include_prefix in the same rule, might it avoid this problem and be easier, faster & more direct to use `includes` instead? The more I think about your case the more I wonder if that's going on.

That said there are two sub-issues here that I don't want to conflate:
The first is whether `includes` might be better for your use case and workaround this issue.
The second is whether the symlink based handling is working for virtual includes--which I think will primarily be used with strip_include_prefix, when there's no direct path we could point to--and whether that's good enough.

-Chris

**Comment by johngkhs** [comment]
Thank you so much for all the details. I did verify that the the virtual headers that the language server goes to are indeed symlinks like you said, and changing them does change the original files. There are just a few strange quirks still with these virtual headers that makes them less preferable for me than going to the actual file if possible:
1) The language server in neovim doesn't seem to attach automatically for these files, whereas it does if I use the hardcoded "src" include hack and go to the actual files (will need to investigate that a bit more, I'm sure it is fixable on my side somehow and is probably unrelated to the bazel-compile-command-extractor project).
2) If jumping around through the filesystem, it is a little jarring to be deep in that bin virtual_includes folder if I want to explore elsewhere from the current buffer.

I was able to find that we do modify the include_prefix for all of our subtargets, we do something similar to this:
      // For a file like src/math/math_util.h, it can be included everywhere in the project as "math/math_util.h" (even in the math subtarget itself)
      include_prefix = "/".join(package_name.split("/")[1:])
I'm not sure if there is another better way to achieve this - using regular includes=["src"] seems like it might be able to achieve a similar goal like you said.

**Comment by cpsauer** [comment]
Thanks for checking! I'm glad to hear the symlinks do indeed resolve to the original files on your system, too, so edits will stay in sync.

IMO the best workaround here is exactly that: `includes=["src"]` instead of `include_prefix`&`strip_include_prefix`. That'll lead to the file being included at its original location and also cuts complexity from your code and symlinking during building. It's also more direct: It sounds like the intent is to search for headers under the existing `srcs` directory and that does it directly. (include_prefix and friends are heavier machinery to allow for inclusion from paths that don't yet exist in the source file tree.)  

I'm a little loathe to otherwise patch around this in this tool, since there isn't actually an equivalent path we can point to in the source tree except in the case where the `include_prefix` should probably better be handled as an `includes` (either by the user or by bazel under the hood).

Instead, I think the longer-term, non-workaround fixes might need to be implemented at other layers, and I'm hoping to ask for some of your help on them, both for your team in the future and for others.
1. Neovim's LSP really should be made to attach to out-of-tree files (consider also browsing to a system-installed header) and symlinked files. Not sure which of those is the issue here, but could I ask you file an issue (or PR) with them on that to get it fixed? If useful, VSCode (at least) handles these cases well already.
2. There's an opportunity for Bazel's implementation to auto-optimize `include_prefix`&`strip_include_prefix` to `includes` when they refer to a preexisting folder. Might be worth filing an issue, just because the fix should be pretty easy for them and be a performance optimization without making the user think about which attribute to use.

**Comment by johngkhs** [comment]
Thank you for all your help throughout this process - everything you suggested makes a ton of sense to me. I have filed two issues

https://github.com/MaskRay/ccls/issues/929: fix ccls's inability to attach to files in bazel-out (I verified clangd does work, while ccls does not)
https://github.com/bazelbuild/bazel/issues/17591: prefer to use already existing directories when possible rather than virtual includes.

I will close this issue now as it is not related to this tool directly, and once again thank you so much for everything!

**Comment by cpsauer** [comment]
Thanks you, John, for writing those and scoping further. My pleasure. Sorry the right long-term fixes are at these other layers.

To close the learning loop for me: Did the switch to `includes` indeed work as a workaround for now?

Cheers,
Chris

**Comment by johngkhs** [comment]
Yep, the includes workaround does work for me. Thank you!
