### ISSUE TITLE
Generated compile commands are missing includes

### ISSUE THREAD

**Issue by SoftwareApe** [hedronvision/bazel-compile-commands-extractor#108]
## Missing headers

I found some similar sounding issues, like https://github.com/hedronvision/bazel-compile-commands-extractor/issues/70, but none seemed to be quite the same.

I get this error when running sonar-scanner with the generated compile commands:

```log
/usr/include/c++/8/cmath:45:15 'math.h' file not found
```

When running the offending compile command directly I get this from GCC:

```log
In file included from <...>
/usr/include/c++/8/cmath:45:15: fatal error: math.h: No such file or directory
 #include_next <math.h>
               ^~~~~~~~
compilation terminated
```

Since this normally compiles I'm assuming the compile command generated is wrong in some way, however I can't quite figure out why.

## Digging deeper

I used `bazel build -s` to compile the target while printing subcommands. Diffing the subcommand I found mostly some quoting differences, e.g. `-DEIGEN_MAX_ALIGN_BYTES=16` vs `'-DEIGEN_MAX_ALIGN_BYTES=16'`, which I don't think matter terribly, and one extra option which caught my eye.

## The mystery

The extra option in the subcommand version is `-fno-canonical-system-headers`. To my naïve eyes this looks like it could be doing something with the system headers. There's even a related issue here https://github.com/clangd/clangd/issues/1004.

[What does GCC say this does?](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html):
>When preprocessing, do not shorten system header paths with canonicalization.

Still no idea if this is relevant in any way.

The bazel build exited successfully. The subcommand was nearly the same. But using the different subcommand didn't really help resolve the issue.

If I run the same subcommand that bazel purportedly runs, I get the same issue with `math.h` missing. What am I not seeing?

**Comment by cpsauer** [comment]
Hey, Carl!

I'm guessing environment variable differences between the build sandbox and your shell environment would be the next thing to check here. Your impulse to run the command separately was exactly the right one to narrow things down, IMO. Thank you for being thoughtful about bisecting the issue.

To double check my understanding: Both the command extracted by this tool and the command from bazel -s fail when run from your shell, but not when run under bazel build, right?

If I'm reading that right, and both commands fail when run in the shell, that makes me think think the error isn't coming from any of massaging this tool does to de-bazel it for consumption by other tools. I wonder if the shell is getting a different gcc or otherwise getting different default include options from the environment? Some settings to check for in your .bazelrc include --incompatible_strict_action_env, which basically blanks out the environment except for a fairly restricted PATH like /usr/local/bin:/usr/bin:/bin:. 

So more concretely, the next experiment I'd run in your shoes is to try blanking out the environment in and running the command. So something like
`env - PATH=/usr/local/bin:/usr/bin:/bin:. <command>` and see if that works. If it does, then I'd run `env` and see which environment variables might be the cause-or try running your tools under a similarly empty env?

Cheers,
Chris

P.S. The `-fno-canonical-system-headers` mystery I can solve, though I suspect it's not relevant if the command isn't working in your shell even with it. We explicitly, intentionally omit it because clangd chokes on it. (Just search for 1004 in refresh.template.py for notes and code) https://github.com/hedronvision/bazel-compile-commands-extractor/issues/21 is the issue here that lead that issue to be filed and the workaround added.

**Comment by SoftwareApe** [comment]
Hi Chris,

except for `-fno-canonical-system-headers` the compile commands are indeed the same as what bazel subcommand prints.

I did some more sleuthing and found these threads:
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71090
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70936
* https://gcc.gnu.org/onlinedocs/gcc-4.9.4/cpp/System-Headers.html#System-Headers

I didn't find any explicit includes for `/usr/...`, but I did see in the second thread that they had `-isystem` includes. Bazel also produces a lot of `-isystem` includes. Interestingly if I replace `-isystem` with `-I` the compile command works.

I still don't understand why the subcommand works in the Bazel sandbox, or if Bazel actually executes what it shows me here. I still find the whole thing a bit sus, but at least now the compile commands work with GCC, Clang and SonarQube.

So I can confirm that the `-fno-canonical-system-headers` is definitely not what keeps it from compiling. So I'd consider this closed here.

Best regards,

Carl

**Comment by cpsauer** [comment]
Hmm, sus indeed. I'm *pretty* sure you're getting the exact command bazel would run (up to the environment) with -s or aquery.

I do know, though, that GCC does reference some environment variables for header searching--and this really does set of my spidey-senses for an include_next kind of problem. As examples, there's CPATH, C_INCLUDE_PATH, CPLUS_INCLUDE_PATH, OBJC_INCLUDE_PATH, GCC_INCLUDE_DIR, referenced [here](https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html).

Anyway, I should probably tap out, as you say, but good luck! Please, for my learning, do tell me if you figure it out.

**Comment by cpsauer** [comment]
Any luck with these, Carl?
