### ISSUE TITLE
refresh_compile_commands needs to be run after every build

### ISSUE THREAD

**Issue by sohaiberrabii** [hedronvision/bazel-compile-commands-extractor#110]
Hi,

Thanks for the great tool. It works smoothly on neovim (only struggled a bit because i didn't notice the `--query-driver=**`).

However, i am wondering why external headers break every time i run a bazel build.
Even if there are no changes, i still have to rerun the refresh_compile_commands to get it working again.

**Comment by cpsauer** [comment]
Hey, Sohaib! You're very welcome. Thanks for giving the tool a go.

That's definitely unexpected--I'm going to guess the problem/fix is a bazel flag mismatch between the invocations. That is, can you make sure that you're passing in the same flags when extracting commands (see README) as you are when you're editing?

If that's not it, we're gonna need to look a little deeper to figure out what's going on. What happens to the //external link when you build? Does it resolve to the same place? Are the headers in question still there?

Cheers,
Chris

**Comment by sohaiberrabii** [comment]
I did check the path of the header when i was investigating but it is the same. 

The bazel build flags are being being set through a `--config=android_arm64` defined in .bazelrc, maybe thats the problem? I do get a warning when refreshing, the warning is about a file not generated in `bazel-out/host/....` when it should only care about `bazel-out/android-arm64-v8a-fastbuild/...`. 

Another thing to note is that the problem concern the included headers from a generated protobuf header:
```
// file1.cc
#include "foobar.pb.h"

// foobar.pb.h
#include <google/protobuf/port_def.inc> // <- not found by clangd after every build
```

**Comment by cpsauer** [comment]
Hmm. That particular warning still makes me think it's a configuration mismatch between the build and the extraction via this tool, since during extraction, it is looking for something generated for the host (though it's possible it's a tool or something). No need to worry about things in .bazelrc, since those will automatically get applied uniformly to both. But, since I see you're building for android, any chance you're using rules like android_binary that configure the build graph, but still running `:refresh_all` instead of using the `refresh_compile_commands` rule to extract from your top-level, configuring target? (I'm referring to [this part of the readme](https://github.com/hedronvision/bazel-compile-commands-extractor#3-often-though-youll-want-to-specify-the-output-targets-you-care-about-andor-what-flags-they-individually-need-this-avoids-issues-where-some-targets-cant-be-built-on-their-own-they-need-configuration-on-the-command-line-or-by-a-parent-rule-an-example-of-the-latter-is-an-android_library-which-probably-cannot-be-built-independently-of-the-android_binary-that-configures-it).) 

Otherwise, I'm afraid I'm going to need to ask you to debug some more on your own--or get me a mini or public example I can debug on. It's hard to debug these from a distance, and I don't think I'm going to be able to guess much better than that without more information!

**Comment by sohaiberrabii** [comment]
At the end it was just a silly mistake from me. As I'm using neovim I couldn't use `--compile-commands-dir=${workspaceFolder}/`, and it seemed to work without it. However that is only because `bazel run` on py_binary seems to symlink all the workspace files in the output directory (including compile_commands.json). The symlinks are removed after running `bazel build` again.

It was fixed after specifying the compile-commands-dir as the working directory with `vim.fn.getcwd()`.

**Comment by cpsauer** [comment]
Yay! Glad to hear things are now working for you. Sounds like there's a non-trivial setup step there. Any chance you'd be willing to pay it forward by writing up some neovim instructions for the README, based on your experience, parallel to the vscode ones? I'm sure it'll help a bunch of people following in your footsteps.

**Comment by cpsauer** [comment]
@sohaiberrabii?
