### ISSUE TITLE
Support pointing to bazel binary when bazel is not on PATH

### ISSUE THREAD

**Issue by johngkhs** [hedronvision/bazel-compile-commands-extractor#117]
Hi,

For my project, we use a custom bazel wrapper script which we do not put on our $PATH, and delegates to the actual bazel binary (also not on our $PATH). Calling the compile commands extractor with the bazel wrapper script fails with a "No such file or directory: bazel" error. Among other things, the wrapper script forcibly clears out the $PATH before running the actual bazel binary, so I can't easily prepend to $PATH either. Is there a way we can pass the bazel binary path to hedron compile commands rather than hardcoding it here:
```
    aquery_args = [
        'bazel',
         ...
    ]
```

Falling back to attempt ./bazel would work for my specific use case since I am in the same directory as our local bazel wrapper script, but it seems like it would be nicer if I could pass the path explicitly like so:
```
./bazel run @hedron_compile_commands//:refresh_all --path-to-bazel ./bazel
```

Let me know what you think. Thank you.

**Comment by cpsauer** [comment]
Hey, John. Good to hear from you again. A tricky recursive case. 
(This reminds me a bit of #84.)

Could we backtrace your goals to find the optimal fix? What are the goals behind these wrappers blanking out the PATH--and, for my curiosity, behind the wrappers more generally?

(While we can add that if we need to, I'd think a wrapper like that might cause you pain more generally. So I'm wondering if I should learn more about the need or if there might be a better way. As an example, if the goal were to protect the action environment from differences that would cause cache misses, maybe `build --incompatible_strict_action_env` in .bazelrc would do it, possibly combined with `--action_env=PATH=`?)   

Thanks,
Chris

**Comment by johngkhs** [comment]
Hello again! Right now the wrapper script does some bootstrapping for us (i.e. downloads our designated version of bazel locally if it doesn't exist, unsets most environment variables to make the build more hermetic, etc.). For this problem, the wrapper script looks approximately like this:
```
export PATH=/usr/bin
exec /path/to/local/bazeldir/bazel "${@}"
```
We actually do set "build --incompatible_strict_action_env=true" in our .bazelrc, so I'm actually not sure what's going on here exactly. I tried printing out $PATH from within a bazel rule and it prints "/bin:/usr/bin:/usr/local/bin", which doesn't match the exported PATH in the wrapper script presumably because we already have "--incompatible_strict_action_env=true"?. If I hardcode "export PATH=/usr/bin:/path/to/local/bazeldir" above (what I've been doing thus far), then hedron compile commands does find the bazel binary and works successfully. So I guess the python binary running hedron compile commands is receiving that exported PATH, even though bazel itself does not?

**Comment by cpsauer** [comment]
Yeah sorta! So `build --incompatible_strict_action_env` handles making the *build* more hermetic, but would still pass the environment through to final binaries being bazel run. Sounds like that might just get you what you want already?  (+ maybe bazelisk to auto-download the version of bazel you want)?

**Comment by johngkhs** [comment]
I was hoping there is a solution which would not involve hardcoding anything in the wrapper script if possible, just by passing command line args instead. I've tried a bunch of attempts like the following, but no luck so far:

./bazel run --incompatible_strict_action_env=false --action_env=PATH=$(pwd) @hedron_compile_commands//:refresh_all -- --incompatible_strict_action_env=false --action_env=PATH=$(pwd)

The only thing that works is changing the PATH in the wrapper itself.

**Comment by cpsauer** [comment]
Hey, John. Yep! I get it.

Again, can do, but how about just ditching the problematic wrapper and accomplishing its goals as follows:
- Controlling the build environment for hermeticity: Goal already accomplished w/ `build --incompatible_strict_action_env` in your .bazelrc
- Download and booststrap Bazel: Use the [Bazel-recommended Bazelisk](https://bazel.build/install/bazelisk) instead.
(And if you need more customization from a shell script, there's tools/bazel, documented in Bazelisk's readme.)

If that solves your needs, it'd move you back towards more standard tools that are likely to work with more things--this included. (And if not, I'd love to learn about the additional needs!)

---

To clarify why the command line you listed above didn't work: The action-env flags affect the *build* actions, but not the running of the final binary under `bazel run`. The idea behind those flags (instead of an env-blanking wrapper script) is that you get a hermetic build but still get the power of environment variables with your final output--which I think is exactly what we want here.

---

I'm hoping I'm not frustrating you too much with my hesitance to add the flag. Again, I'm trying to understand if there's a more general need here for wrappers like this--or whether it's more of a one-off and would be better satisfied by a change in your configuration.

Cheers,
Chris

**Comment by johngkhs** [comment]
Thanks and makes sense - I can definitely work around this. Our wrapper does do other things I think are valuable enough to warrant keeping it for now, but I think we can potentially move towards a more standard solution for the things I mentioned above.

I still think it's a slightly unintuitive requirement for this tool to require bazel to be on the PATH, especially if I am executing bazel directly (as you said, it would be nice if we could directly pass the bazel binary I am running along to the python script, but that isn't possible).

I will close this issue for now as the PATH workaround will do the trick for us. Thanks again for your help!
