### ISSUE TITLE
Clangd doesn't find generated protobuf headers

### ISSUE THREAD

**Issue by LCJebe** [hedronvision/bazel-compile-commands-extractor#128]
Hi! Thank you very much for providing this awesome tool! We use it every day in our team and it makes our lives easier.

I have the following directory strucure containing a C++ test target, and a protocol buffer that I'm using inside it:

```
project/
|-- image_metadata/
    |-- BUILD
    |-- image_metadata.proto
|-- pipeline/
    |-- BUILD
    |-- pipeline_test.cpp
    |-- pipeline.cpp
    |-- pipeline.h
```

`image_metadata/BUILD`: 

```
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "image_metadata_proto",
    srcs = ["image_metadata.proto"],
)

cc_proto_library(
    name = "image_metadata_cc_proto",
    visibility = ["//visibility:public"],
    deps = [":image_metadata_proto"],
)
```

`pipeline/BUILD`:

```
cc_library(
    name = “pipeline",
    srcs = ["pipeline.cpp”],
    hdrs = ["pipeline.h”],
    deps = [
        "//image_metadata:image_metadata_cc_proto",
    ],
)

cc_test(
    name = "pipeline_test",
    srcs = ["pipeline_test.cpp"],
    deps = [
        ":pipeline",
        "@com_github_google_googletest//:gtest_main",
    ],
)
```
The compile commands run without error or warning.
The generated header is included inside `pipeline/pipeline.h` like this: 
```
#include "image_metadata/image_metadata.pb.h"
```
but it's not resolved by clangd (using extension for VSCode): 
```
'image_metadata/image_metadata.pb.h' file not found
	clang(pp_file_not_found)
```

I built the target, and the `image_metadata/image_metadata.pb.h` exists in Bazel's build folders, e.g., 
`bazel-out/darwin_arm64-opt/bin/image_metadata/image_metadata.pb.h`
`bazel-bin/image_metadata/image_metadata.pb.h`

I'm fairly new to Bazel and compilation databases, so any help would be appreciated! Please let me know if you need more information.

Thank you!

**Comment by cpsauer** [comment]
Hey, Lars! Great to meet you. I'm smiling hearing that you are getting value out of this tool, doubly as another Stanford computer vision person. Looks like you're off at Adobe now, but if you're ever crossing through campus, come say hi!

It's always hard to guess right from a distance--but to try to shortcut things, not being able to find a generated header is often from mismatches in the flags passed when building the generated files and when running this tool, since that changes the bazel-out subdirectory the generated files are expected in. But in that case this tool should have printed a helpful warning, so maybe it's something else. Did the flags part part of the README make sense?

I think the best way to narrow it down would be to take a peek at the generated compile_commands.json. When you look at the entry for `"file": "pipeline/pipeline.h"`, does it have an entry to add that subdirectory of bazel-out to the header search paths? That is, is there an `"-iquote",\n "bazel-out/darwin_arm64-opt"`, or is the -iquote to another subdirectory of bazel-out?

Just to save a potential round trip, could you also let me know what command you're running for the build and for this tool?

Cheers,
Chris

**Comment by LCJebe** [comment]
Hi Chris! Great to meet you too. I'm currently working remotely from Germany, but I'll return to the Bay later this year and I'll come say hi then!

You were exactly right. I should have read the flags section in the README more carefully. I did specify the same flags, but of course I forgot the extra `--`. It became obvious when checking the search paths as you recommended: The path was `"bazel-out/darwin_arm64-fastbuild"` instead of `"bazel-out/darwin_arm64-opt"`, because of the incorrectly passed flag. Makes a lot of sense in retrospect! I'm not sure why the warning didn't appear though. It appeared again after a `bazel clean --expunge`.
 
 It works now! And I learned how to debug header search paths myself! :) Thank you very much!

**Comment by cpsauer** [comment]
:) Delighted to hear that resolved it, with (hopefully) some fun, future-valuable learnings, too. I occasionally travel there too to visit family--yes, please drop me a line when you're back in the Bay.

Backtracking to try to improve things for future folks: On warnings, I'm going to guess that it probably only printed it the first time because of our internal caching, but I think we can do better, printing even on subsequent runs when we check the cache. I'll put that on my list.

Cheers!
Chris
