### ISSUE TITLE
ModuleNotFoundError: No module named 'refresh_compile_commands'

### ISSUE THREAD

**Issue by k355l3r-5yndr0m3** [hedronvision/bazel-compile-commands-extractor#137]
Executing `bazel run :refresh_compile_commands` produces this error. 
```
Traceback (most recent call last):
  File "refresh_compile_commands.check_python_version.py", line 15, in <module>
    import refresh_compile_commands
ModuleNotFoundError: No module named 'refresh_compile_commands'
```
I'm using the latest commit (ecafb9672f43462f073e76f0e3436dbad1f600e6)

**Comment by cpsauer** [comment]
Hey! Thanks for giving the tool a try and for writing in.

We're using the same commit internally (as you'd expect) and I'm not seeing the same error, unfortunately; I'm having trouble reproducing. I also tried running it in an empty bazel project and things ran successfully with both the latest bazel rolling and stable releases; so it's not dependent on some quirk of our .bazelrc.

Any idea what might be different about your setup? Some super old bazel version? Does it run cleanly in an empty project?

All the best,
Chris

**Comment by k355l3r-5yndr0m3** [comment]
[bazeltest.zip](https://github.com/hedronvision/bazel-compile-commands-extractor/files/12312371/bazeltest.zip)
running `bazel run //binA:refresh_compile_commands` from root directory emits the error as above. The version of bazel I use is 6.1.0, but the same issue is present in 6.3.2. However `bazel run @hedron_compile_commands//:refresh_all` is fine and does not produces any error.

**Comment by cpsauer** [comment]
Aha! 🤦🏻‍♂️ Yep, so the issue is that, in trying to get a better error message for folks who try to run this under very old python versions, I inadvertently broke support for calling refresh_compile_commands in sub-packages.

Most people put it in the top level BUILD file (probably because of the recommendation in the readme), so it'd gone unnoticed. Thanks so much for taking the time to bring it to my attention and help me understand.

I've pushed up a commit that I think will fix things. Could I ask you to give them a try and tell me how it goes?

**Comment by k355l3r-5yndr0m3** [comment]
Yes, (e16062717d9b098c3c2ac95717d2b3e661c50608) appears to fix it.
