### ISSUE TITLE
-fno-canonical-system-headers is a problem with clangd

### ISSUE THREAD

**Issue by matta** [hedronvision/bazel-compile-commands-extractor#21]
I'm not sure what the best fix for this issue is, but I thought I'd report it so at least the workaround I came up with is easier to find.

I'm running bazel on Debian Testing. By default on this system bazel uses the system compiler, which is gcc/g++, and passes it the `-fno-canonical-system-headers` flag. The flag ends up in my `compile_commands.json`, which then passes it to `clangd`, which issues a warning about the unrecognized command line argument.

The bazel code that sets this up is https://github.com/bazelbuild/bazel/blob/e1a912c5af5b4bb3ac9d722bd3857ddbbc03f1db/tools/cpp/unix_cc_configure.bzl#L233-L240

According to [clangd's documentation](https://clangd.llvm.org/config#compileflags) this can be worked around with something like this in a `.clangd` file:

``` yaml
CompileFlags:
  Remove: -fno-canonical-system-headers
```

I found that this fixes things for clangd, but not other clang tools. For example, clang-tidy still has an issue with `-fno-canonical-system-headers` -- it refuses to continue.  So, I tried this hack to remove the flag from `compile_commands.json` and it seemed to work:

``` sh
sed -i 's/ -fno-canonical-system-headers / /g' compile_commands.json
```

The best fix is likely to generate `compile_commands.json` with bazel configured to use clang++ instead, but I haven't tried that.  The second best fix is for all clang tools to support (or ignore) `-fno-canonical-system-headers`, like they do for most every other gcc flag.

The third and fourth best fixes might be to:

- handle this in bazel-compile-commands-extractor, maybe even going as far as handling a `CompileFlags` modifier as described here: https://clangd.llvm.org/config#compileflags
- recommend that people handle it the way I did above, with sed (or similar)

**Comment by cpsauer** [comment]
Hi, Matt! Thanks so much for using the tool, for writing in so thoughtfully about this, and for helping others yesterday. Sorry this didn't just work out of the box for you.

Way to track it down to the source. Let's make this case great for you and everyone else.

Here's my take: 
- I think we should definitely file an issue about this over at https://github.com/clangd/clangd.
  - They're great, and this seems like something clangd itself would want to handle gracefully--at a minimum, by ignoring it. This flag seems to come up more than enough. 
  - I think that issue should also address clang-tidy, since they bundle it. But maybe ask if we should also file the clang-tidy half of the issue somewhere else.
  - Would you be down to file this clangd issue?
- Until they've fixed it, I think we should embed the equivalent of your sed command, but in extract.py.
  - I'd propose we add it to _all_platform_patch, parallel to the existing case, with noting down both the clangd issue and this issue. https://github.com/hedronvision/bazel-compile-commands-extractor/blob/main/extract.py#L190-L200
    - Should be a super good first change. Like one copy-paste line, plus comments.
    - Happy to do, but I don't want to steal your thunder, since you've tracked it this far. Want to toss up a PR and get on the contributors list?

All the best,
Chris

---

As a P.S., some notes about the paths not taken:
- I think we don't want to make everyone do separate configuration for this when we can easily handle it automagically.
  - My concern especially with .clangd is in it not applying to files outside of tree. As an example, if you ctrl+click into a system header, then .clangd is no longer in an ancestor directory and (at least used to) not apply. Curious if that edge case rears up in your experience.
- I think we should do the fix in extract.py rather than just appending your sed line to refresh.sh.template for two reasons:
  - refresh.sh.template, and our dependency on bash, are probably on the way out to facilitate Windows support.
  - More minor, but there's the usual cross-platform sed trickery, though you'll see plenty of that already in refresh.sh.template.

**Comment by matta** [comment]
I filed a clangd issue here: https://github.com/clangd/clangd/issues/1004

**Comment by cpsauer** [comment]
Wahoo! Thank you!

**Comment by cpsauer** [comment]
Sounds like we're all set--but if this, or something else--rears its ugly head, please lmk

**Comment by cpsauer** [comment]
@matta, I noticed in your issue that you'd mentioned you were using clangd with emacs. 

If you think there are key gotchas people should know when setting things up with emacs, any chance I could ask for your help in adding those to the README?

Thanks,
Chris

**Comment by cpsauer** [comment]
@matta, more privately over here, I thought I'd ask: anything I should know or learn from your moving on from working with this stuff? Would really value your candor.
(If it makes it safer, just post and then delete. I'll still get the email.)

**Comment by matta** [comment]
Lots of reasons:

1. I'm a semi-retired ex-googler, programming for fun and self enrichment, in recent years. If anything gets un-fun at any point I have the privilege of being able to walk away, rather than pound on things until they work. Working with C++ was mostly interesting for me because I got to play around with new C++ features for a while, but it was just a step on a journey that included obscure stuff like messing with Smalltalk and Common Lisp (and coming to my own conclusions about why those languages "lost" and are not widely used today, despite the cries of their fervent advocates).
2. Bazel is a classic example of an "open source second" project for Google. It exists to provide an insular and quite elegant build system for a large organization with dedicated build and tooling teams. I worked on the C++ library team at Google and saw the benefits first hand. However, it is not a quality product for smaller efforts. Case in point is this project. Google doesn't care enough about "external world" problems like supporting oh, I don't know, extremely popular IDEs or build systems everybody else uses, because Google has solved the problem in a different way internally. Google doesn't really "get" what it means to support developers in the same way that, say, Microsoft or Apple does.
4. If one has to self support the build system on a small project I've found it better to swim *with* the current and use what most everybody else is using, which is *not bazel*, even if it sucks more on theoretical grounds, because most of the problems you run into are both understood and solved before you encounter them.
5. Same goes for C++. It is a great industrial programming language, but it isn't necessarily fun. A long long time ago, when there was a debate to be had about the merits of Intel's 8086 vs Motorola's 68k architectures, a co-worker of mine explained why he loved coding for his M68k Amiga on the weekend much more than the 8086 programming we did at work. He said "You'd have to pay me to work with a segmented address space. In fact, people do!". That is how I feel about C++. When you need it, you need it. I'm glad I know it. Use it by choice, for simpler hobby programming tasks, well, not so much.
6. Lately I've used Go.  ;-)

**Comment by cpsauer** [comment]
Makes total sense. Thanks, Matt, for taking the time to explain so eloquently. Helps this more junior dev learn :) If you ever write anything about your language learnings--or are willing to share--I for one would love to learn from your explorations.
