### ISSUE TITLE
Not detecting c++ version

### ISSUE THREAD

**Issue by klementtan** [hedronvision/bazel-compile-commands-extractor#32]
In my `.bazelrc` I set the C++ version by adding the following:
```
build --cxxopt='-std=c++20'
```

however when I run `bazel run @hedron_compile_commands//:refresh_all`, it does not detect the c++ version and sets `-std=c++11` in my `compile_commands.json`. This causes clagd to be unable to detect > c++11 features.

**Comment by cpsauer** [comment]
Hi, @klementtan! Thanks for trying the tool, and sorry to hear it's giving you trouble. I appreciate your writing in. Let's get this figured out.

I think I'm going to need a little more info, though. We've got (basically) the same thing internally and it seems to pick up fine. I just messed around for a little bit trying to reproduce, but things seemed to work. Any chance you have something you could share? Like ideally a repo I can clone, but maybe a folder or something? Happy to promise to not share if you want to give private access.

[I also want to make sure that the -std=c++11 entry you're looking at *isn't* for dummy.cc, which seems to be a separately configured artifact of bazel, that shouldn't influence autocomplete. That one indeed fails to configure from .bazelrc, but shouldn't matter.]

All the best,
Chris

**Comment by klementtan** [comment]
Hi, @cpsauer! Thanks for replying so quickly.

I realized that I was wrong and there was a `-std=c++20` flag in `compile_commands.json` as well. However, the `compile_commands.json` produced was unable to let `clangd` detect some c++20 features (ie `std::construct_at`) as compared to other tools that were able to generate the correct `compile_commands.json` for `clangd` to detect `std::construct_at`.

<details>
<summary>bazel-compile-commands-extractor's compile_commands that is unable to detect std::construct_at</summary>

```
  {
    "file": "kstring.hpp",
    "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang --language=c++ -D_FORTIFY_SOURCE=1 -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG -std=c++11 -fdebug-prefix-map=/private/var/tmp/XXXXX/685022d1502307c0ff38764901841155/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/hedron_compile_commands/refresh_all.runfiles/__main__=. -iquote . -iquote bazel-out/darwin-fastbuild/bin -iquote external/com_google_googletest -iquote bazel-out/darwin-fastbuild/bin/external/com_google_googletest -iquote external/bazel_tools -iquote bazel-out/darwin-fastbuild/bin/external/bazel_tools -isystem external/com_google_googletest/googlemock -isystem bazel-out/darwin-fastbuild/bin/external/com_google_googletest/googlemock -isystem external/com_google_googletest/googlemock/include -isystem bazel-out/darwin-fastbuild/bin/external/com_google_googletest/googlemock/include -isystem external/com_google_googletest/googletest -isystem bazel-out/darwin-fastbuild/bin/external/com_google_googletest/googletest -isystem external/com_google_googletest/googletest/include -isystem bazel-out/darwin-fastbuild/bin/external/com_google_googletest/googletest/include -MD -MF bazel-out/darwin-fastbuild/bin/_objs/kstring_test/kstring_test.d -frandom-seed=bazel-out/darwin-fastbuild/bin/_objs/kstring_test/kstring_test.o -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -mmacosx-version-min=12.1 -no-canonical-prefixes -pthread -std=c++20 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__=\"redacted\"' '-D__TIMESTAMP__=\"redacted\"' '-D__TIME__=\"redacted\"' -target x86_64-apple-macosx -c kstring_test.cpp -o bazel-out/darwin-fastbuild/bin/_objs/kstring_test/kstring_test.o",
    "directory": "/Users/XXXX/codes/personal/learning/cpp/string_cpp_tmp"
  },
```
</details>

<details>
<summary>Alternative compile_commands.json that is able to detect std::construct_at</summary>

```
  {
    "command": "external/local_config_cc/wrapped_clang -D_FORTIFY_SOURCE=1 -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG -std=c++11 DEBUG_PREFIX_MAP_PWD=.  -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks -mmacosx-version-min=12.1 -no-canonical-prefixes -pthread -std=c++20 -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -target x86_64-apple-macosx -iquote . -iquote bazel-out/darwin-fastbuild/bin -x c++ -c kstring.hpp",
    "directory": "/private/var/tmp/XXXX/40dd52e6bfedb4c3deeb69f147bb0e90/execroot/__main__",
    "file": "kstring.hpp"
  },
```
</details>

You can reproduce by:
1. `$ git clone https://github.com/klementtan/string_cpp.git`
2. `$ git checkout 7b8e974c7e82d3c75e05bdb90a31b97172f5ccfd`
3. `$ bazel build :all`
4.  `$ ln -s bazel-out/../../../external .`
5.  `$ bazel run @hedron_compile_commands//:refresh_all`
6. Open `kstring.hpp` in your editor and go to line 435 which should show the error `No member named 'construct_at' in namespace 'std'`

**Comment by cpsauer** [comment]
Hey, @klementtan. 

Super appreciate your good reproduction case.
[Sorry I've been a bit slow here. Took a little birthday breather.]

After some debugging, it turns out that this was still not quite what it seemed! What's happening is that the other (tool's ?) command is sufficiently broken for the purposes of clangd that clangd falls back to some default behavior that happens to handle this case properly.

Why is the other input broken? The problem is that `external/local_config_cc/wrapped_clang` bazel wrapper. Clangd can't introspect it, so it treats it as opaque and falls back. (The wrapper also crashes if you call it without setting special environment variables--and clangd can't make heads nor tails of the __BAZEL_XCODE_* flags. The command differs from this tool because we automatically unwrap the compiler and expand the flags to their true values.) As an example to show that this is what's going on, if you change the compiler in either command to any other executable (let's say `chmod` as an example of something obviously not a compiler), you'll get the same behavior as that alternative command. Even just setting `chmod -std=c++20` as the command will do just as well. Sad times.

Now, that still doesn't solve the original problem. Why does passing the right, de-bazeled, clangd-parseable command, as this tool does, lead to erroneous errors? I'm not sure. This seems to be a clangd issue. I've created a (super minimal) example and filed an issue with them over at (https://github.com/clangd/clangd/issues/1079). 

Thanks for your patience, and sorry I can't directly fix. I'd love it if you'd follow that https://github.com/clangd/clangd/issues/1079 and participate as things move along! As a workaround until things are fixed, would it work to keep using that old compile_commands.json file in the interum? The commands may be broken from clangd's perspective, but at least it seems to give you the desired output behavior.

Chris

P.S. If anyone else sees this and is running into the same thing, please do chime in!

**Comment by cpsauer** [comment]
(Also heads that you don't need to use refresh_compile_commands if you've already specified the flags in .bazelrc. Happened to see your BUILD file while debugging away.)

**Comment by cpsauer** [comment]
^ Since the workaround fixed thing on the test repo you sent me and also was relevant for another issue, I went ahead and added the workaround to the recommended settings in the README and closed this issue.

If that's premature, please say and I'll open this right back up. 

Either way, please do confirm that this solves things for you!

**Comment by klementtan** [comment]
@cpsauer Thanks a lot for the detailed explanation and the solution works for me. Thanks!!

**Comment by cpsauer** [comment]
Yay! Delighted to hear it
