### ISSUE TITLE
Assertion fails and aborts compile commands generation

### ISSUE THREAD

**Issue by alexander-born** [hedronvision/bazel-compile-commands-extractor#34]
Thanks for this great tool!

For specific targets I get an assertion error here: https://github.com/hedronvision/bazel-compile-commands-extractor/blob/1d21dc390e20ecb24d73e9dbb439e971e0d30337/refresh.template.py#L90

```

AssertionError: Something went wrong in makefile parsing to get headers. First entry should be the source file. Output: 
interpolator_fuzz_test.o: \
  external/host_ros_clang_toolchain/lib/clang/11.0.1/share/asan_blacklist.txt \
  test/interpolator_fuzz_test.cpp \
...
```

Not sure, but it seems that the source file is not the first but the second entry?

**Comment by cpsauer** [comment]
Hey, Alexander! Thanks for using this tool and for writing in. Sorry there's a rough edge here that's breaking things for you.

On the positive side, the assert is doing its job, catching an unexpected case before it gets silently problematic. That way we can fix it. Good job assert.

That said, I'm probably going to need a little help, though, since this interesting case is getting triggered by some stuff in your setup, so you've got the good test case.

Is this (host_ros_clang_toolchain) a custom toolchain you guys have written? Looks like it's using an [asan ignore list](https://clang.llvm.org/docs/SanitizerSpecialCaseList.html), here called asan_blacklist.txt. I'd expect an `-fsanitize-ignorelist=asan_blacklist.txt` somewhere in the command, yeah? I hadn't considered that case, but it makes sense that it'd show up as a dependency...but I certainly hadn't expected it to come first.

Could I ask you to confirm that the flag above was part of your command? And then try the latest commit I just pushed to see if things now work for you?

Thanks,
Chris

P.S. that commit auto closed the issue (optimistically). But if that turns out to be premature, and things are still broken, just holler, and I'll open this right back up.

**Comment by alexander-born** [comment]
Unfortunately the issue persists. If I get rid of this argument by slightly modifying your commit it works.
```
'-fsanitize=undefined,address'
```

```diff
     # Strip sanitizer ignore lists...so they don't show up in the dependency list.
     # See https://clang.llvm.org/docs/SanitizerSpecialCaseList.html and https://github.com/hedronvision/bazel-compile-commands-extractor/issues/34 for more context.
     header_cmd = (arg for arg in header_cmd
-        if not arg.startswith('-fsanitize-ignorelist='))
+        if not arg.startswith('-fsanitize'))

```
If I get rid of these by modifying your mentioned commit the issue is resolved. Not sure if this is the correct way to go.

**Comment by cpsauer** [comment]
Oh bummer. Sorry.

Am I right in reading that asan_blacklist.txt is never specified on the command line, then? (If so, wild!)

This still does feel like the right fix to me, since this is just for finding the headers used in a file, not for the command emitted. Does that seem okay to you? Please let me know if you think there's something I'm missing.

[I'd better crash; it's very late here. But I'll reply in the morning.]

**Comment by cpsauer** [comment]
It might be handy to see the problematic command if you can get it, by going into //external and temporarily commenting out the assert, for example.

**Comment by alexander-born** [comment]
Yes the `asan_blacklist.txt` is nowhere to be found the the variable `compile_args` of `__get_headers`.

I modified the assert to print out all the relevant variables in `__get_headers` to find the argument `-fsanitize=undefined,address`.

Thanks for your help and good night :)

**Comment by cpsauer** [comment]
Great. Sounds like we should land your change then! Want to get your name on the contributors list? If so, toss up a quick PR and I'll merge it in. Otherwise I'll do it in the morning. (I'm on my phone now.)

Thanks for being both great and kind :)

**Comment by alexander-born** [comment]
Opened a PR.

**Comment by cpsauer** [comment]
Pretty sweet first PR if I may say so myself. Thank you! (And goodnight!)
