### ISSUE TITLE
🎉 100 Stars!

### ISSUE THREAD

**Issue by sam-hedron** [hedronvision/bazel-compile-commands-extractor#39]
This isn't an issue per se, but rather a celebration of a great product.

Congratulations on reaching 100 stars! 🎉

This wonderful tool is only possible thanks to the tireless efforts of superstar author and maintainer @cpsauer.

If you've interacted with Chris at all (@lixiaoquan, @aapeliv, @JKurland, @HaberR, @pqn, @lummax, @DominicTobias, @aminya, @jwbee, @matta, @rshanor, @LoSealL, @alksi, @johnzeng, @klementtan, @alexander-born, @jun-sheaf, and countless more), you'll know how helpful, responsive, and friendly he is.

There aren't very many repositories where the author preemptively opens (and then resolves!) outstanding issues (#1-#6, #8), notices and incorporates the progress of external forks (#9, #33), and interacts with and empathizes with users and contributors (too many to count).

He's far too humble to write this post - so that's what I'm here for.

Go Chris, and go hedronvision/bazel-compile-commands-extractor!

<3 Sam

**Comment by cpsauer** [comment]
Wahoo! 🌟  

Thanks, Sam--and all of you! I really appreciate everyone who's spent time with this tool and am thankful for all of you who've helped make it better with issues and code (many tagged above). Way to go, team. Together we've gotten something useful off the ground!

Cheers to great developer tools! 🍻 

-Chris

P.S. If you're reading this, remember to update for the latest goodies! One important (manual) change is adding the query-driver flag. See the README :)

**Comment by cpsauer** [comment]
Thanks all for the love! I'm going to close this down with a highlight: Windows support just landed. Huge thanks to @lummax for laying the foundations and getting it rolling. I'm excited to see what we all do together here.

To facilitate that Windows support, there's a (minor) interface change that all you core users should know about so you aren't surprised. Since symlinks are weird/different on Windows, the tool now takes charge of creating and managing the symlink for you across platforms. To that end, please move it out of your source control!

Something like (from your workspace root):
1) `rm external`
2) stage that deletion, so external is no longer checked in
3) grab the [latest commit of the tool](https://github.com/hedronvision/bazel-compile-commands-extractor/commits/main)
4) run the new tool. It'll recreate external (unstaged) and add some essentials to your .gitignore to keep it that way.
5) Commit those ignore changes and the removal of the external symlink.

Onwards and upwards!
Chris
