### ISSUE TITLE
Improving confusing behavior when flags are passed to the refresher build

### ISSUE THREAD

**Issue by aminya** [hedronvision/bazel-compile-commands-extractor#41]
I have been using the extractor with GCC with no issue. But when I try to use Clang, I get a lot of errors that are like this:

```shell
clang-13: error: no such file or directory: 'bazel-out/k8-fastbuild/bin/external/sdformat/src/EmbeddedSdf.cc'
clang-13: error: no input files
clang-13: error: no such file or directory: 'bazel-out/k8-fastbuild/bin/external/yaml_cpp_internal/drake-src/convert.cpp'
clang-13: error: no input files
...
```

These external packages are the dependencies of another package.

**Comment by cpsauer** [comment]
Hello again, @aminya! Thanks for persisting--and sorry we're hitting some issues here.
Still great to have you here with us--and still a pretty amazing GitHub contribution profile you have.

Offhand, my hypothesis might be that the extractor is gracefully handling the lack of generated files before a build (as it tries to), but that we're not messaging it well enough to the user. But it's hard to tell without more info :)

Is the resulting compile_commands.json non-empty and well-formed? That is, does the tool crash, or just print those errors while it runs, searching for the headers used in your code?

Do those files indeed not exist? If you run a build with clang, do the missing files get generated?

(I'd love it if you'd try for me bc I'm moving as fast as I can on some other improvements. But if you're still stuck, maybe get me a mini example that I can play with?)

Thanks,
Chris

**Comment by aminya** [comment]
> Hello again, @aminya! Thanks for persisting--and sorry we're hitting some issues here.
Still great to have you here with us--and still a pretty amazing GitHub contribution profile you have.

Thank you so much! 😊

> Offhand, my hypothesis might be that the extractor is gracefully handling the lack of generated files before a build (as it tries to), but that we're not messaging it well enough to the user. But it's hard to tell without more info :)
> Is the resulting compile_commands.json non-empty and well-formed? That is, does the tool crash, or just print those errors while it runs, searching for the headers used in your code?

As far as I remember, the script generates a `compile_commands.json`.

> Do those files indeed not exist? If you run a build with clang, do the missing files get generated?

These files do not actually exist! The build succeeds with Bazel, but not the extractor.

> (I'd love it if you'd try for me bc I'm moving as fast as I can on some other improvements. But if you're still stuck, maybe get me a mini example that I can play with?)

Yeah, totally. I will prepare an example. However, I am afraid that It will take a few days. 
Thanks for your support. I will update you with more information.

**Comment by cpsauer** [comment]
Sounds good. LMK.

One thing to keep an eye our for: When you run a build, does it create those files? And then do subsequent runs of the extractor succeed?

**Comment by aminya** [comment]
It seems the issue is `k8-fastbuild`. The files exist under `k8-opt`. So the extracted is picking up the wrong `opt` configuration.

**Comment by cpsauer** [comment]
Oh! Okay, I know what's going on here. Thank you! (No need to do more minimal repro work)

**Comment by cpsauer** [comment]
And my initial guess was wrong :)

Here's what's going on:
1) The --config=release build generates the files under opt, as you'd expect.
2) The compile commands extractor is *itself* being built with your release config, but when it queries Bazel, it doesn't use those same flags (because it doesn't know what they are). To specify flags for targets, right now, you have to pass them in the dictionary in refresh_compile_commands. (.bazelrc is picked up automatically)
3) Therefore, the Bazel defaults to returning the commands for fastbuild, which don't have generated files for them yet.
[I don't think this is different with clang vs. gcc, so I'm still perplexed if you're seeing a difference there.]

Here are the next steps I think we should take:
1) Better messaging when there are errors finding headers, indicating that it might be because they're generated files.
2) Seeing if we can pick up the flags that were used in the original build and auto-apply them, making this case work as you'd expected. (Not sure if Bazel will let us access them.)
3) If we can't do (2), improving the README and error messages to guide people to the right answer. We *could* more easily handle the case where people do, e.g `bazel run @hedron_compile_commands//:refresh_all -- --config=release`, but I'm not sure it's worth it since people won't be putting that extra `--` in there by default anyway. 
  a) FWIW [this was the part of the README](https://github.com/hedronvision/bazel-compile-commands-extractor#2-often-though-youll-want-to-specify-the-output-targets-you-care-about-this-avoids-issues-where-some-targets-cant-be-built-on-their-own-they-need-configuration-on-the-command-line-or-by-a-parent-rule-an-example-of-the-latter-is-an-android_library-which-probably-cannot-be-built-independently-of-the-android_binary-that-configures-it) that was supposed to explain this, but clearly not well enough. 

Thoughts?

Right now, I need to finish out the Windows stuff before I implement. But I'll be back!

If you'd be down to help: You could research whether there's a way for Bazel rules (or files being run under Bazel) to automatically get all the flags that were passed to the Bazel invocation. I didn't see one (hence building it this way), but that's what we'd need to automate away this error case fully.

**Comment by cpsauer** [comment]
I see your 👍🏻! (does that mean that the workaround worked? That is, passing the flags in refresh_compile_commands)

**Comment by cpsauer** [comment]
And you, too, @DanielEliad. Does that mean you're running into the same?

**Comment by cpsauer** [comment]
For (2), after some research, I don't think Bazel lets us. 
(That is, there isn't a way for our rule to read all the flags passed into it. If someone finds one, please say!)

So I'm working on better error messaging to guide people to the right solution.

**Comment by cpsauer** [comment]
Hey guys! Just pushed up a commit hopefully making things clearer here.

I added better messaging around the warnings, added support for passing flags via `-- -flag` as in (3), above, and revamped the README to match.

Could I ask you to give it a try and tell me if it would have guided you to the right solution? If not, I'd love your advice on how to improve it

**Comment by cpsauer** [comment]
(Given your thumbs ups I'm going to [optimistically] close this. But please do write back about what you think! And if there's still an issue, I'll reopen :)

**Comment by aminya** [comment]
Hi @cpsauer, thanks for the response. I tested this with your suggestion, but it doesn't fix the issue.

```
bazel run refresh_compile_commands -- --config=release --compilation_mode=opt
```

I still get:
```
clang-13: error: no such file or directory: 'bazel-out/k8-fastbuild/bin/external/sdformat/src/EmbeddedSdf.cc'
clang-13: error: no input files
clang-13: error: no such file or directory: 'bazel-out/k8-fastbuild/bin/external/yaml_cpp_internal/drake-src/binary.cpp'
clang-13: error: no input files
```

I am also not sure if the extractor picks up `.bazelrc` flags. For example, I have to pass the `--cxxopt=-std=c++17` again in the Build file
```
refresh_compile_commands(
    name = "refresh_compile_commands",
    targets = {
        "//:my_target": "--cxxopt=-std=c++17",
    },
)
```

**Comment by aminya** [comment]
Oh, I was wrong. I also needed to upgrade the extractor package to the latest commit. Now it works 🎉 Thank you!

**Comment by DanielEliad** [comment]
Thank you so much!
Works like a charm for me too :tada:

**Comment by cpsauer** [comment]
Wahoo! Glad to hear it guys. You're very welcome. Please do keep me in the loop about how things go!

On update: I would *strongly* recommend setting up Renovate make it easy to keep things up to date (see the README). That way you'll always have the latest as more improvements continue to land.
