### ISSUE TITLE
codegen dependency

### ISSUE THREAD

**Issue by bsolomon-bw** [hedronvision/bazel-compile-commands-extractor#45]
Hi -- some targets in our build generate .pb.cc files from Protobuf type definitions.  I noticed that without actually running those builds, we don't have those generated files yet, and the hedron scan fails.  I was able to get around it by building those targets, but I'd like to be able to specify them as `deps` of the `refresh_compile_commands` rule in our BUILD so that those builds actually get run before running the scan.  Is there a way to do that?

**Comment by cpsauer** [comment]
Hey, @bsolomon-bw! Honored to have your account's first issue.

Right now, there isn't an auto-build option, but that doesn't mean there can't be :)

First some questions: 
1. I'm curious, did the warning messages do an okay job guiding you to run a build if you wanted to? I added those recently and haven't gotten to discuss them with someone who's run into them. 
2. I also want to make sure that by "fails" you mean printed those warnings--rather than crashing. Is that right? Was a valid compile_commands.json produced, just missing the headers of the files that hadn't been generated yet? Or did the scan crash?

The basic idea had been that we were trying to not assume the code builds, nor require a full build each time (for speed). So the tool just bumps along and does its best, letting you know if it thinks a build might make things better by generating missing files. The idea here also is that the user will *keep* having to run builds if they'd like the newest versions of their generated files, so we'd better get them thinking about generated files before they start wondering why there are red squiggles under their includes.

[We can certainly add an option to auto-build before scanning, but I think the user will still need to think about generating files--and usually old files are ok. Separately, if you know a way to run a build that *just* generates files or missing files, that could be very powerful indeed.]

What do you think?

Cheers!
Chris

**Comment by bsolomon-bw** [comment]
side note -- is there any way to prevent this tool from modifying our .gitignore?

**Comment by cpsauer** [comment]
Hi @bsolomon-bw!

So the good news is that, even without a build, the scan is, in fact, succeeding, despite those warnings! Its output should be very usable for editing, with only slight limitations, especially after your first build. (Tell me if that's not what you're seeing!)

[Do you think we should rephrase or recolor those warnings to make it more clear that things are continuing gracefully?]

The problem with using `deps` is that it'd **require** the code to be able to build for you to analyze and edit it. We definitely don't want that, since it's pretty common that you end up refreshing the database mid-refactor to get better autocomplete with the new code structure. 

If you always want to run a certain, manual subset of builds before this tool, what about instead wrapping that and your invocation of this tool in a shell script? (Don't use, e.g. Bash's -e; continue on error.)

-Chris

**Comment by cpsauer** [comment]
Some background thoughts I'm having--verbose and detailed enough that I'll separate them out:

We could certainly add an option for the tool to try to run the full builds it analyzes before it analyzes them. That'll still hit cache and everything. And we can continue even if those builds fail. Basically automatically doing exactly what it suggests you do in the warning. But crawling the build graph and automatically generating the missing source files...that'd be much trickier, I think, because they might depend on auto-configuration in parent rules that we don't want to build.

I'm also not yet convinced that automatically building everything is really better than just asking the user to run the build if they want to. My thinking: It's okay if files haven't been generated yet, and we want to handle that case. Hence yellow warning rather than red error. I think, more often than not, you don't want to run a build: This tool just needs some indicative source rather than a fresh build--and most of the time the user has already run a build at some point over the parts of the codebase they care about. Probably they want to quickly browse without building everything (might take quite a while!). And auto-building won't get the user out of having to run builds ever so often to keep generated the files up to date. They'll be editing->building->editing->building already probably, much more frequently than they run this tool. There's also an issue where they've got a flags mismatch, mentioned in the warning, which we can't otherwise auto-detect, and that'll cause problems when browsing the source.

If you think I'm wrong, and you'd still really like this option, lmk! Not hard to add--but I'm a bit concerned about whether it's going to be better than prompting people to run the build

**Comment by cpsauer** [comment]
Re gitignore: Not currently, but we could add one. The auto-ignore is a bit of a new feature, since it's easy to get hosed if you try to, e.g., delete a junction on Windows (deleting everything inside it...) or push the external link between platforms, so I figured I'd try to automate it.

Would it work to just use the entries it adds? (The reason you might prefer the * over individual entries is that they can get renamed as people pass different flags.) More generally, what do you think we should do here?

**Comment by bsolomon-bw** [comment]
I see the thinking re. skipping absent outputs -- that does make sense, I think.  For the gitignore -- perhaps it would be simple enough to check for a match against a looser regular expression, rather than using exact comparison, since people might already have special rules in place for their particular repos.  Personally, it's lower-priority, but I figured it wouldn't hurt to ask if you'd already thought of it!

**Comment by cpsauer** [comment]
Totally! And I really appreciate the feedback in general and on the new-sub feature.

This stuff is tricky, and I wish it were less of a tradeoff than it is. Seriously, I'd *love* your help if you see a better way to communicate about codegen to people encountering it for the first time, since you just went through it. 

Similarly on the gitignore stuff--but I can't think of a case where different lines would substitute without a subtle issue. [Assuming the user is using git.] Perhaps that's the problem--we could add comments to the gitignore explaining each line?

**Comment by cpsauer** [comment]
@bsolomon-bw, any thoughts on how we should communicate these better?
[Otherwise, seems like we should close this down?]

**Comment by cpsauer** [comment]
I added some code so the gitignore adder automatically explains itself with comments. Curious what you think https://github.com/hedronvision/bazel-compile-commands-extractor/commit/7764ce33aa0c3514d53f0fa168152cd6d9a816b5

Otherwise, I'm going to (optimistically) close this down for now, unless I hear from you otherwise!
