### ISSUE TITLE
header-only targets

### ISSUE THREAD

**Issue by lromor** [hedronvision/bazel-compile-commands-extractor#50]
Hi! Awesome project! I really appreciate the quality of it.
I have a problem. Maybe it's a known issue but I'm not sure how to debug it.
I noticed that if I create header-only targets in bazel, for instance something like:

```starlark
cc_library(
    name = "foo",
    hdrs = [
        "foo.h"
    ],
    deps = [
        "@com_google_absl//absl/types:optional"
    ]
)
```

Doesn't seem to include the header `absl/types/optional.h` in the compile_commands.json. It looks like aquery is somehow skipping this target as it's not a compilation unit. And maybe doesn't properly generate the right compiler flags. What are your thoughts, maybe I'm missing something?

**Comment by cpsauer** [comment]
Aw, thanks! Yeah, this is a tricky one.
(Sorry to be a little slower than usual--got pulled away onto other tasks for a few days.)

To explain the behavior you're seeing: With header-only libraries, there's no compilation being run unless you use or test them. So technically, the "right" compile_commands.json is an empty one. Similarly, aquery is happily informing us that it's not going to run any compilation actions for that library unless someone uses it. 
(Now, we do currently try to add entries for all headers used in source files that are compiled to work around a clangd issue. More generally, handling of headers and header-only libraries is a weak point in current clangd, because it's input format is based around compile commands. Still, most projects have at least one route to compile their code.) 

Easiest workaround? Just use the library from somewhere and infer the commands from that. So, for example, make a cc_test or test with a .cc file that includes the .h, and then extract compile commands from that. That'll create at least one compilation action for the tool to infer things from. 

Do you think we should add something about this to the readme/docs?
[Or alternatively, if you can think of a better fix, I'm all ears!]

Cheers!
Chris

**Comment by cpsauer** [comment]
I added a little bit about this to the README and docs in https://github.com/hedronvision/bazel-compile-commands-extractor/commit/d3cbc6220320e8d2fce856d8487b45e639e57758

But I'd still love to discuss with you! Do you think that sentence would have been enough? How can we make this case better for people?

**Comment by lromor** [comment]
Hi @cpsauer ! I love your energy and exhaustive answers. It feels like there's no simple way to solve this using compiler commands, so as a user, I'm satisfied with your readme update. 

>  the "right" compile_commands.json is an empty one

Interesting, as far as you know, are other IDEs or compile_commands generators trying to overcome this issue?

**Comment by cpsauer** [comment]
Thanks, @lromor! :)

Not that I know of offhand, which is sad. But in my experience, I usually end up building my code somewhere, so it resolves. (I've had this issue across a pretty wide variety of editors over the years--so I understand what you're hitting.) I totally agree that it's a fairly fundamental issue with basing things on compile commands. I think this could be a great thing to raise for discussion over at clangd, if you'd be down!

Anything else I should know before we close this? Just to check, was the assumption right that the code was being built somewhere, but that we needed to guide people to specify compiling targets in `refresh_compile_commands`? Basically, I wish this worked automagically, but I *think* code that's never compiled is a rare case, so we should steer people to specify the compiling target. If that's wrong, I'd definitely like to know.

**Comment by lromor** [comment]
Yes, your assumption was right. I'll close it.
