### ISSUE TITLE
--query-driver leading to wrong default includes

### ISSUE THREAD

**Issue by liushiqi9** [hedronvision/bazel-compile-commands-extractor#51]
System version : Macos Monterey 12.1 

Problem:
With default settings mentioned in README.md, clangd counld find many system headers like stdlib.h. And in VSCode 
```
#include <iostream>
```
will be marked error.

Solved with: 
"--query-driver=/usr/bin/clang++" 

Maybe mention this in README.md, and it might save people a couple of hours. 

clangd problem is mentioned [here](https://github.com/clangd/clangd/issues/487)

**Comment by cpsauer** [comment]
Hey, @liushiqi9! Thanks for trying the tool--and for writing in to make things better and smoother for others.

To confirm, did the `--query-driver=/**/*` from the README not work? 
[I'd have thought that regex would match and have you covered. It was intended for this and similar cases. See, e.g., https://github.com/clangd/clangd/issues/1079]

Cheers!
Chris

**Comment by cpsauer** [comment]
I'm going to close this (optimistically), since it seems likely that `--query-driver=/**/*` would have covered this case, and I haven't heard back from you.

But seriously, if you tried `--query-driver=/**/*` and it wasn't working, please say something so we can fix this. I'll reopen it and jump right back in with you.

**Comment by liushiqi9** [comment]
Hi, @cpsauer , sorry for the late reply.  Didn't check github for couple of days. 

Yes, I firstly followed the README and set **--query-driver=/**/*** but it didn't work. 

It only work with **"--query-driver=/usr/bin/clang++"** for some reason( I am not sure why).

**Comment by cpsauer** [comment]
Yikes. Okay, reopening.

**Comment by cpsauer** [comment]
@liushiqi9, I'd really love your help tracking this down more if you're willing! Different compilers will have different paths, so we really want to figure out how to make the wildcard cover your case. May also save you pain with other projects.

Could I ask you to look at the clangd output, with and without your query driver?
(If in VSCode: View -> Output and select clangd in the dropdown)
You'll probably have to restart clangd in between. (CMD+SHIFT+P for the command pallet and "restart clangd")

There should be lines in there about query driver. I'd love it if you could try to figure out why the --query-driver=/**/* isn't matching, or how we might best cover the case you've found.

**Comment by cpsauer** [comment]
When I open mine, the lines look like
```
System includes extractor: successfully executed <compiler>
    got includes: <...>
```

**Comment by cpsauer** [comment]
Thanks for reporting, and thanks so much in advance for checking things out!

**Comment by liushiqi9** [comment]
With  --query-driver=/**/* setting, we got result below: 
`
E[23:01:52.096] System include extraction: invalid file type for 
I[23:01:52.097] ASTWorker building file /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/iostream version 1 with command inferred from test/test.h
[/Users/imac/workspace/test]
external/local_config_cc/cc_wrapper.sh
-U_FORTIFY_SOURCE
-fstack-protector
-Wall
-Wthread-safety
-Wself-assign
-Wunused-but-set-parameter
-Wno-free-nonheap-object
-fcolor-diagnostics
-fno-omit-frame-pointer
-g
-MD
-MF bazel-out/darwin-dbg/bin/test/_objs/test.pic.d
-frandom-seed=bazel-out/darwin-dbg/bin/test/_objs/test.pic.o
-fPIC
-iquote .
-iquote bazel-out/darwin-dbg/bin
-isystem thirdparty/fmt-8.1.1/include/fmt
-isystem bazel-out/darwin-dbg/bin/thirdparty/fmt-8.1.1/include/fmt
-Werror=sign-compare
-Werror=return-type
-Werror=unused-variable
-Werror=unused-but-set-variable
-Werror=switch
-march=native
-fdiagnostics-color=always
-Werror=reorder
-no-canonical-prefixes
-Wno-builtin-macro-redefined "-D__DATE__=\"redacted\"" "-D__TIMESTAMP__=\"redacted\"" "-D__TIME__=\"redacted\""
-c
-isystem /usr/local/include
-isystem /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include
-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include
-isystem /Library/Developer/CommandLineTools/usr/include
-isystem "/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks (framework directory)"
--target=x86_64-apple-darwin21.2.0
-resource-dir=/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6
-x c-header
-std=c++20 /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/iostream`

And as we can see the -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include is not correct. It should be -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1.

With --query-driver= setting, we got result below: 
`I[23:05:58.336] ASTWorker building file /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/iostream version 1 with command clangd fallback
[/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1]
/Library/Developer/CommandLineTools/usr/bin/clang -xobjective-c++-header /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/iostream -resource-dir=/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6`
which works.

**Comment by cpsauer** [comment]
Hey @liushiqi9, thanks for the logs and for sticking with it so we can try to fix this for everyone else. Something strange is going on here.

A few more things to try so we can figure this out:
- Could you try it *without any* query-driver flags and report back on the logs and whether it works as well? (I suspect it will, which might be surprising.)
  - Could you do these (all) tests on a file with a source extension, like .cc or .cpp, just to eliminate a variable?
  - The most important logs are those starting with "System include"
- And could you check to make sure external/local_config_cc/cc_wrapper.sh exists when --query-driver=/**/* fails?
- And if so, could you try executing it with, e.g. --version, and see what happens?

Just to double check: I assume you're using the latest clangd (14.0.3), despite having an older version of clang, right? And *not* using Apple's clangd?

---
Other thoughts in my head:
- Interestingly, on my system, using Xcode instead of CommandLineTools, I'm seeing clang as the compiler, instead of clang++, and query-driver=/**/* is working fine. Hence my asking you all these questions to try to figure out what's going on.
- It looks like your compiler is still wrapped by bazel from the `cc_wrapper.sh` above, so "--query-driver=/usr/bin/clang++" shouldn't be matching it anyway. Realizing this is what spawned the questions above.
- From the error you posted "System include extraction: invalid file type for" in the first log (see code [here](https://github.com/llvm/llvm-project/blob/175833ed6f62b697ce6248930da54e4ddb7f4c00/clang-tools-extra/clangd/QueryDriverDatabase.cpp)) I think clangd is failing to run query-driver for extensionless C++ headers, since the switch [here](https://github.com/llvm/llvm-project/blob/b9f3b7f89a4cb4cf541b7116d9389c73690f78fa/clang/lib/Driver/Types.cpp#L293) will say the extension is invalid. I'll file a quick issue with clangd about this, but it might not be the root issue.

Cheers,
Chris

**Comment by cpsauer** [comment]
@liushiqi9, if you're still there, they have a theory over in the clangd issue I filed for you! https://github.com/clangd/clangd/issues/1173

It's still worth the above tests--and maybe try opening a cpp file first and see if that fixes things, to test their hypothesis.

**Comment by liushiqi9** [comment]
1. Without any query-driver flags the clangd looks good, and no error is in the clangd logs. I search for "System include" and nothing shows up. 
2. `which clangd` shows `/usr/bin/clangd` and `clangd --version` shows `Apple clangd version 13.1.6 (clang-1316.0.21.2.5) Features: mac+xpc`
3. With --query-driver=/**/*, which fails, external/local_config_cc/cc_wrapper.sh exists. run --version with it returns `Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`
4. In all the tests I did above, I did open a .cpp file first. 
5. With -query-driver=/**/*,  I find out that `#include <iostream>` or `#include <string>` in .h files has error, but in .cpp files it doesn't have any error. Without any --query-driver flags, no error occured.

**Comment by cpsauer** [comment]
Aha! Okay. So that confirms that hypothesis. 

Looks like you're using Apple clangd, which is older and has some issues. Could I ask you to grab the latest version of clangd (and this tool) and see if that fixes things?

[As background, there was an issue about language detection fixed in clangd 14. We used to have an automatic workaround for it, but removed it when clangd shipped their fix. And I'm wondering if you're hitting that old issue and if it's mistakenly thinking your header is a C file instead of C++.]

**Comment by liushiqi9** [comment]
Upgrading clangd into lastest version 14.0.3 fixed this issue. 
Issue closed.

**Comment by cpsauer** [comment]
Yay! Great. Delighted to hear that resolved things.

[I'll add some notes about Apple clangd to the readme in the morning.)
