### ISSUE TITLE
Why it is compiling my code?

### ISSUE THREAD

**Issue by lixin-wei** [hedronvision/bazel-compile-commands-extractor#53]
I have a huge Bazel repo and I want to generate `compile_commands.json`.

After I run `bazel run @hedron_compile_commands//:refresh_all`, I found it is compiling my code, a lot of ccplus processes have been started:

![image](https://user-images.githubusercontent.com/19600697/170211853-90e390b0-cb98-46b1-bac6-01f4e35b1374.png)

My question is **why does it need to compile my code?** I believe that we can get the compile commands without compiling the source code.

Besides, compiling my code needs a long time (about 15 minutes), so it takes a long time to generate `compile_commands.json`.

**Comment by cpsauer** [comment]
Hey, @lixin-wei! Thanks for using the tool and writing in.

Good question. We sure can get the compile commands for your code without compiling it. Indeed, this tool works even when you code doesn't compile.

So what's going on here? We're preprocessing your code (much faster than compiling!) to figure out which sources include which headers. This lets us tell clangd which build settings should be used for those headers, which it fails to figure out a lot of the time by default. This is what #5 and the ["behind the scenes" part of the README](https://github.com/hedronvision/bazel-compile-commands-extractor#smooth-edges--what-weve-enjoyed-using-this-for) are supposed to be about, but they wouldn't be obvious if you discovered it this way.

This is on by default because I suspect you want us to do this for you. It gets you great autocomplete in header files, rather than clangd's flaky behavior with out us that leads to lots of false errors. Basically, we're automatically working around clangd's biggest issue for you.

If you're down to help out, there's a great way we could cache this header finding and really speed things up. It's mentioned in #5 and in comments in the code, but I'd be delighted to coach/explain further, of course. Please say something if you're open to helping!
Otherwise, there're the workarounds in #5, but it basically just that you might find you don't need to regenerate compile_commands.json very often (which is true).
Finally, very soon, we'll merge in the option to disable this preprocessing and header finding. This is most useful for the people who want to use ccls instead of clangd, since ccls doesn't have the same problem clangd does. (You could switch, and I'd recommend that over using clangd with the header finding off, but I think there are other reasons to prefer clangd over ccls, especially long term). We'll also be adding the option to just include compile commands for your workspace, which should really speed things up if you have lots of dependencies. 

Anyway, please let me know what you're thinking. And really, I'd be awesome to have your help if you'd be willing.

Cheers,
Chris

**Comment by lixin-wei** [comment]
I see, thank you so much for such a detailed explanation!

Instead of getting worng autocompletion, I'd rather wait for it.

And I agree with your idea about adding cache to it. It will save a lot of time! Give me some time to read #5 and check whether I can help to do something.

**Comment by cpsauer** [comment]
You're very welcome. Thanks for being great yourself--and for reaching out on LI!

**Comment by cpsauer** [comment]
The basic idea is to check Bazel's .d file listing the headers.
We'd need to (1) make sure the .d is a fresh cache by checking that no files listed in it have been modified since it was last modified. And (2) run our current header finding and overwrite it if it wasn't fresh.

**Comment by cpsauer** [comment]
(Need to go to bed soon over here, but I'll reply more in the morning.)

**Comment by cpsauer** [comment]
@lixin-wei, any thoughts? Any chance the caching is something you'd be excited about and willing to help out with?

**Comment by lixin-wei** [comment]
Hi! Sorry I suddenly got tons of tasks to do in my work (cry, So maybe I can't help in a short time. I'm very sorry about it. I'll be back once I'm free!

**Comment by cpsauer** [comment]
That's okay! Good luck! Cheering you on with whatever's on your plate.

**Comment by cpsauer** [comment]
I'll close this for now, then, since there's a main issue elsewhere. But thanks for filing! I bet others will come along with the same question and this will be a great resource.

**Comment by cpsauer** [comment]
@lixin-wei, heads that I just landed the fixes I was talking about above--and more! Header finding should be way faster and cached.

(We now have caching for header file generation and for clang/gcc, piggyback on Bazel's dependency cache--in addition to options to control header finding. See the readme for those.)

That should be a huge improvement in speed. Curious to hear what you think!

**Comment by lixin-wei** [comment]
@cpsauer Wow, that's awesome! Let me upgrade and try it!

**Comment by lixin-wei** [comment]
@cpsauer I tried the latest commit, but it seems it still takes a long time when I run `@hedron_compile_commands//:refresh_all` the second time.

Anything I can provide you for your to debug?  This is my project: https://github.com/ray-project/ray, just run `bazel run @hedron_compile_commands//:refresh_all`. Before that, you need to change the commit ID in the `bazel/ray_deps_setup.bzl:312` first.

**Comment by lixin-wei** [comment]
@cpsauer I tried it and the time boosted from 20min to 4mins in the second time. Nice job, thank you very much!

But I think 4 min is still a little bit long. Maybe we can make it faster. I'll have a look at where the time is consumed when I'm free.

If you are willing to have a try you can use my repo: https://github.com/ray-project/ray

Just run `@hedron_compile_commands//:refresh_all` in the root dir. Before that you might need to update the commit ID in `ray_deps_setup.bzl:312`

**Comment by cpsauer** [comment]
Oh bummer. Glad it helps some, but yeah, 4m is still pretty long.

I've really got to sleep now, but I'd love it if you'd profile it and tell me if you see any good opportunities.

Some other ideas:
Did you get a chance to try try exclude_external_sources or any of those other tricks? (See README for more.) Might be handy because it looks like you've got a lot of sizable dependencies.
If you'd previously built, I'd expect even the first run to have mostly hit (bazel's internal) cache. Might be worth checking that you're building and running this extractor with the same flags? (If you've got everything automatically in .bazelrc then ignore that one.)

Also, looks like a super neat and successful project you've got over there. Pretty cool!

-C

**Comment by cpsauer** [comment]
Aha! Figured out one way to speed things up in the cached case, and pushed some improvements.

[I woke up realizing that, while checking cache freshness, we must be re-checking the modified times for common headers a gazillion times, and that they couldn't be being cached beneath us because the file system is volatile. I then verified that a bunch of runtime was going there via a profiler, and then memoized our calls to mtime, really speeding things up in the cached case. Now, at least on my repos, the runtime is almost entirely waiting for bazel to respond to our aquery and python's json library dumping compile_commands.json to disk.]

When you get a chance, I'd love it if you'd let me know if it speeds things up for you!
[^ Tricks above still relevant for the first run.]

**Comment by lixin-wei** [comment]
@cpsauer Oh genius dude! It boosted to 20s! The first run also speeded up to 5 minutes! Awesome! 

I'll upgrade immediately! Our team has already been complaining about the speed haha. Thank you very much for your job!

**Comment by lixin-wei** [comment]
I think you can update the default commit ID in README to the latest commit. Or creating a release tag? It's a huge improvement!

**Comment by cpsauer** [comment]
Yay! I'm so glad.
Thanks for posting back. It made my day.

**Comment by cpsauer** [comment]
And to confirm, that big of a speedup without using exclude_external_sources, right?

**Comment by cpsauer** [comment]
And will do on the commit in the README. Glad you think it's a big enough improvement to be worth that :)

I'd been trying to get people to just treat the latest commit as the version they should use--but I suppose I should make sure to update the hash in the README every so often.

Could I ask for your honest feedback about the release process? Anything I should know, or ways to make it better? Curious also what makes Renvate not a good option--maybe the need for admin permissions?

Cheers & thanks,
Chris

**Comment by lixin-wei** [comment]
> And to confirm, that big of a speedup without using exclude_external_sources, right?

Yes

> Could I ask for your honest feedback about the release process? Anything I should know, or ways to make it better? Curious also what makes Renvate not a good option--maybe the need for admin permissions?

Yeah I can't use Renvate because I have no admin access. Besides, it's better to depend on a fixed version in software engineering.

For releasing, In my opinion, I think maybe it's better to have a version number. It will make the product look more 'professional'. For minor and untested commits, just leave it in the master branch. When you think it has a huge improvement, then test it and release a new version number in GitHub's release tag. And you don't need to update README again and again. Just tell users: 'find the latest version in the release tag.'

**Comment by cpsauer** [comment]
Got it. Thanks so much for your honest feedback. It's super useful for me to accumulate understanding of how things are used and thought about. For example, great for me to confirm that hypothesis about admin access.

For now, I am going to stay commit-based, but I'll keep thinking about it and collecting info. In the meantime, know that each commit to main stands on its own as a tested improvement, so you can always be confident in using the latest.
