### ISSUE TITLE
How to add new language support?

### ISSUE THREAD

**Issue by cloudhan** [hedronvision/bazel-compile-commands-extractor#61]
I built a native starlark rules [rules_cuda](https://github.com/cloudhan/rules_cuda). Practice show that this compile_commands.json generator works pretty well (Great work :) ).  So I'd like extend it for my rule, maybe in a private fork, since it is not widely adopted now. Any suggestion?

**Comment by cpsauer** [comment]
Hello again, @cloudhan! Great to hear from you. Thanks for your kind words.

Cool that you're building some rules for cuda. Cuda is on my mind because @abcdabcd987 tossed up a great PR that involved cuda in TensorFlow this last week (#58), making it so we could handle a variation in makefile dependency syntax.

Speaking of tensorflow, any relation between your efforts and https://github.com/tensorflow/runtime/tree/master/third_party/rules_cuda? I'd love to better understand the current state of cuda support in Bazel. I'd also be curious how people decide between nvcc and clang for cuda.

**Here's how I'd advise getting started adding support for cuda and your rules:**

If you haven't already, it's worth quickly reading the relevant parts of https://github.com/hedronvision/bazel-compile-commands-extractor/blob/main/ImplementationReadme.md and getting set up to edit the code.
1. Start by telling the tool to examine actions ingested by your rules.
To do this, add your mnemonic to our action query. In your case, that's changing
https://github.com/hedronvision/bazel-compile-commands-extractor/blob/670e86177b6b5c001b03f4efdfba0f8019ff523f/refresh.template.py#L671
to `f"mnemonic('(Objc|Cpp|Cuda)Compile',deps({target}))",`

2. From there, try running it, and we'll need to see what specific patches cuda needs.
In particular, you should just look at any error messages when running or in the editor. We might need to add command patches for those, like we do in https://github.com/hedronvision/bazel-compile-commands-extractor/blob/670e86177b6b5c001b03f4efdfba0f8019ff523f/refresh.template.py#L540
And we may also need to add some special cases around finding the headers included in files compile with NVCC, if it uses different flags for listing those. But we can figure that out based on the error messages.

I'd be delighted to take a PR--but heads that I'll probably ask for it to be high quality! Better to merge it all in and get the goodies for you and everyone than to have forks diverge--at least as long as you think this'll have a bunch of users down the line.

Good luck! Don't hesitate to write back.

Cheers,
Chris

**Comment by cpsauer** [comment]
(I'm going to close this for now, since it'll mostly be private discussion between us. But don't worry; I'll still be responsive.)

(@abcdabcd987, feel free to unfollow if not relevant, but I tagged you because I thought you might have thoughts we should hear on cuda and bazel. Please say either way!)
