### ISSUE TITLE
Use standard license?

### ISSUE THREAD

**Issue by JamesMBartlett** [hedronvision/bazel-compile-commands-extractor#63]
Hi there,

Would love to use your tool. However, my company (and many other companies) have a blanket ban on using open source software that is not licensed under one of the standard licenses (eg. MIT, BSD-3, Apache, etc). In addition, I work on an open source project that is under the Cloud Native Compute Foundation (CNCF), and CNCF bans usage of any open source projects that are not using one of the standard licenses. It seems like your license is almost exactly the same as the MIT license, but because its not verbatim identical many people can't use your tool. 

If you'd be willing to change your license to a standard open source license that would be great, and I think would enable a lot more people to use your tool.

**Comment by cpsauer** [comment]
Hey, James! 

I feel like I've seen you elsewhere around the internet, but I can't place it. In trying to figure that out, I saw that you did a stint at Whisper.ai--I remember talking to those guys when they were just getting started! Small world.

Would love to find a way for this to be something you can use. But using what we've built here might involve a little bit more flexibility than a verbatim blanket ban, just as it would for lots of other common tools.

For dev tools (rather than underlying dependencies) I'd imagine you all probably choose to use software, like GitHub itself, with other licenses without a problem, right? And I'm going to guess the open-source whitelist is more to protect copyleft licenses accidentally getting in and restricting use of your software? Probably you'd be down to use boost, even though it has its own license?

As you'd noted, this license is really pretty permissive and open--and an effort at making something better by combining some of the best ideas from the games world and elsewhere from those with, e.g., MIT. I'd be pretty surprised if the terms didn't clearly allow for your goals on generous terms and enable working together! If that's not true, I'd love to hear it so we can make it better. And while I totally get the pull of just standardizing on licenses and being done with it--and have done that on other projects--we'd really like to try to keep moving things forward. That's been good enough for Google and a bunch of other folks, and I'm hoping it can be okay with you, too, as a hopefully small cost for using this tool. May it serve you well!

Cheers,
Chris

**Comment by JamesMBartlett** [comment]
Thanks for getting back to me so quickly.

>I feel like I've seen you elsewhere around the internet, but I can't place it. In trying to figure that out, I saw that you did a stint at Whisper.ai--I remember talking to those guys when they were just getting started! Small world.

Small world indeed. No longer work at Whisper.ai, but glad you've heard of them. Working on [Pixie](https://github.com/pixie-io/pixie) now.

>For dev tools (rather than underlying dependencies) I'd imagine you all probably choose to use software, like GitHub itself, with other licenses without a problem, right? And I'm going to guess the open-source whitelist is more to protect copyleft licenses accidentally getting in and restricting use of your software? Probably you'd be down to use boost, even though it has its own license?

The issue is that we have to include the tool in our codebase (via bazel remote repos) and as a CNCF project we have very explicit restrictions about licensing. See [here](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist). I will work on getting ad-hoc approval for this project, but it requires a vote of the governing board which only meets quarterly or so.

>As you'd noted, this license is really pretty permissive and open--and an effort at making something better by combining some of the best ideas from the games world and elsewhere from those with, e.g., MIT. I'd be pretty surprised if the terms didn't clearly allow for your goals on generous terms and enable working together! If that's not true, I'd love to hear it so we can make it better. And while I totally get the pull of just standardizing on licenses and being done with it--and have done that on other projects--we'd really like to try to keep moving things forward. That's been good enough for Google and a bunch of other folks, and I'm hoping it can be okay with you, too, as a hopefully small cost for using this tool. May it serve you well!

As mentioned above, the issue is not really the permissiveness of the license, just that its non-standard. On a meta note, I would argue that moving away from standardized licenses is moving things backward not forward but its your project so your prerogative. 

Seems like you are set in your license decision, fair enough. So I'll close this out and work on getting an individual exemption for this project.

**Comment by cpsauer** [comment]
Yeah! Wow. Honored. Sorry. But thank you for being exceptionally great to work and communicate with.
