### ISSUE TITLE
Failed to get action keys from Bazel

### ISSUE THREAD

**Issue by WSUFan** [hedronvision/bazel-compile-commands-extractor#64]
The command "bazel run --cpu=k8 :refresh_compile_commands" reports an error. What does it mean?
![image](https://user-images.githubusercontent.com/26418940/177432035-4b81121b-a3bf-40b5-9cf9-15d0c97c3dbf.png)

Here is what I have in the BUILD
![image](https://user-images.githubusercontent.com/26418940/177432072-b2b11499-aba8-46ad-9467-b4d95cd4965a.png)

Here is the full log:
![image](https://user-images.githubusercontent.com/26418940/177432136-0840fd46-191b-43dc-84cc-439eeb6c6c96.png)

Any idea? 
Thanks

**Comment by cpsauer** [comment]
Hey @WSUFan! Thanks for trying the tool and writing in.

I've pushed a commit to silence this assert in the case you're in, since it's not firing appropriately here, and to downgrade it to a (recoverable) warning otherwise. Could I ask you to grab the latest and give things a try?

I suspect you'll also want to add `--cpu=k8` to the flags (value) in your refresh_compile_commands--or to .bazelrc if you always build with it. Right now, `--cpu=k8` is just applying to the build of the compile commands script itself, not to the build of `//:packaging` it's examining. (We'd do that automatically if Bazel let us!) So I expect you'd get commands for non-k8, if things default to something else on your machine!

[I know roughly what's happening: Bazel doesn't think it has any cached outputs, and it tells this tool so when we ask it. That's what the log you're seeing says. We were assuming that Bazel always had some cached actions--from building the extraction script at the very least. I'm not sure why Bazel doesn't have those cached actions for you, and I can't get it to reproduce, but we can at least remove that assumption. If you know why bazel has no cached actions, I'd love to know! (different output base, maybe, but I don't see that in your commands here?) ]

Cheers,
Chris

**Comment by cpsauer** [comment]
Out of curiosity:
- Could you run a build and then `bazel dump --action_cache` and see if it still comes out empty? [That'd be very strange indeed.]
- You've also got me curious what this packaging rule does :)

**Comment by WSUFan** [comment]
> Hey @WSUFan! Thanks for trying the tool and writing in.
> 
> I've pushed a commit to silence this assert in the case you're in, since it's not firing appropriately here, and to downgrade it to a (recoverable) warning otherwise. Could I ask you to grab the latest and give things a try?
> 
> I suspect you'll also want to add `--cpu=k8` to the flags (value) in your refresh_compile_commands--or to .bazelrc if you always build with it. Right now, `--cpu=k8` is just applying to the build of the compile commands script itself, not to the build of `//:packaging` it's examining. (We'd do that automatically if Bazel let us!) So I expect you'd get commands for non-k8, if things default to something else on your machine!
> 
> [I know roughly what's happening: Bazel doesn't think it has any cached outputs, and it tells this tool so when we ask it. That's what the log you're seeing says. We were assuming that Bazel always had some cached actions--from building the extraction script at the very least. I'm not sure why Bazel doesn't have those cached actions for you, and I can't get it to reproduce, but we can at least remove that assumption. If you know why bazel has no cached actions, I'd love to know! (different output base, maybe, but I don't see that in your commands here?) ]
> 
> Cheers--and sorry about that, Chris

Hi Chris. Thanks for the quick fix! The --cpu=k8 does not make any difference, it is actually a default value. The project is very large. It has a lot of generated code. So I have to build the whole project first to have those generated codes. That's why I use the output_base option. And this may lead to an improvement. Can we run analysis(pre-build) & compdb in one shot? So that the generated codes can be shown.

**Comment by WSUFan** [comment]
> 

Yeah it still reports zero action cache... not sure why. 
I have tried this command in another project, and it gives me disired outputs...

**Comment by cpsauer** [comment]
Hi :) You're welcome--really wish this were working totally smoothly for you. Thanks for writing back.

First, just to check: The latest commit avoids the crash for you, right? And then prints the warning prompt to build generated files, but still generates a compile_commands.json?

Sounds like k8 was a red herring and that we hypothesize that the real issue is a change in --output_base between runs. Right?

I'd really suggest that you set output base (and other flags that influence the output directory) the same for this tool's queries and your build. That allows the compile_commands.json to correctly refer to all the preexisting generated code and for the referenced code to automatically update as you rebuild...and it allows this tool to hit the action cache for header information, really speeding things up. Conversely, I'd expect a change in output base to cause the action cache--and set of generated files--to come up empty, like we're seeing, since it's no longer pointing to the old output.

I'm having trouble telling from what you wrote whether you're already intending to have the same output base everywhere or not--and how you're setting output base. If the fix isn't clear to you, could I ask you to spell that out a little more clearly for me?

Cheers,
Chris

**Comment by WSUFan** [comment]
> Hi :) You're welcome--really wish this were working totally smoothly for you. Thanks for writing back.
> 
> First, just to check: The latest commit avoids the crash for you, right? And then prints the warning prompt to build generated files, but still generates a compile_commands.json?
> 
> Sounds like k8 was a red herring and that we hypothesize that the real issue is a change in --output_base between runs. Right?
> 
> I'd really suggest that you set output base (and other flags that influence the output directory) the same for this tool's queries and your build. That allows the compile_commands.json to correctly refer to all the preexisting generated code and for the referenced code to automatically update as you rebuild...and it allows this tool to hit the action cache for header information, really speeding things up. Conversely, I'd expect a change in output base to cause the action cache--and set of generated files--to come up empty, like we're seeing, since it's no longer pointing to the old output.
> 
> I'm having trouble telling from what you wrote whether you're already intending to have the same output base everywhere or not--and how you're setting output base. If the fix isn't clear to you, could I ask you to spell that out a little more clearly for me?
> 
> Cheers, Chris

Yes I setup the same output_base for compdb query and build. 
Never mind, the fix is good now. I can generate the compdb. I decide to move forward :D
Many Thanks!

**Comment by cpsauer** [comment]
Glad we got it good enough for your use--but I would really like to better understand what went on here, if you'd be down to help! 
I'm sure you won't be the last to run into this, and it still feels like a mystery why the action cache is being listed as empty after a build with the same output base.
Please do tell me if you have any more ideas or leads!

**Comment by WSUFan** [comment]
> Glad we got it good enough for your use--but I would really like to better understand what went on here, if you'd be down to help! I'm sure you won't be the last to run into this, and it still feels like a mystery why the action cache is being listed as empty after a build with the same output base. Please do tell me if you have any more ideas or leads!

I have no idea why the action cache is listed as empty... And interesting, I cannot reproduce the error using the old commit (even if I clean the cache and do the fresh build)

**Comment by cpsauer** [comment]
On that last one: the tool has built its own caches and is no longer trying to hit Bazel's...but those should be wiped out by a bazel clean.

**Comment by cpsauer** [comment]
Any chance you'd still share with me how and where you're setting the output base?

**Comment by cpsauer** [comment]
Perhaps not--though that's the only thing I can currently think of that would produce this--especially if the setting was somehow not being picked up by our call to `bazel dump`.

I would still love to see how you set output base at the command line or .bazelrc (or wherever else)!

Otherwise, I won't bug you further--except to request that if the cause ever does occur to you, I'd love it if you'd write back here and tell me.
