### ISSUE TITLE
refresh_compile_commands.py has SyntaxError

### ISSUE THREAD

**Issue by liuli-neko** [hedronvision/bazel-compile-commands-extractor#95]
I modify WORKSPACE and new a BUILD file,then run `bazel run :refresh_compile_commands` or run `bazel run :refresh_all` all failed.
![image](https://user-images.githubusercontent.com/67323556/206083041-1728c842-03c8-465c-9ce7-ad9662c6210e.png)
![image](https://user-images.githubusercontent.com/67323556/206083145-e7a0894a-83b0-468e-a466-3756cc2b30c7.png)

**Comment by cpsauer** [comment]
Hey @liuli-neko, since I haven't heard from you in a week, I'm going to close this down. But, if you read this, I'd still love it if you'd reply whether that worked.

It's valuable to know if it was the right fix, so I can help the next guy. And if you're still having trouble, then I'd be happy to open this issue right back up and help.
