### ISSUE TITLE
What is the lowest required bazel version?

### ISSUE THREAD

**Issue by hitvery** [hedronvision/bazel-compile-commands-extractor#98]
I am using Bazel 0.24, for some reason it is hard to update basic infrastructure in my organization...
So does anyone have experience apply this great tool with old Bazel version? Or maybe we can provide a lowest required bazel version in the document for people ready to use?

**Comment by cpsauer** [comment]
Hey, Wong! Thanks for writing in and for your interest in using this tool.

I know we have people using it on some quite old versions, maybe as old as 2.1 last I heard.

But so many Bazel issues have been resolved since those early prerelease versions of bazel that I really think the solution is for you guys to update to a more recent version. I probably shouldn't spend much time working around old issues to ensure backwards compatibility--but if you want to run the tool on your version and see if it works, I'd be happy to take backwards compatibility patches if they're small. That's what we did for the guy using 2.1.

More generally, the strategy is to make sure things work on recent versions; taking reverse compatibility patches if easy. If you think we should so something else, please do say. More generally, just because I'm about to close this doesn't mean our discussion can't continue.

Cheers,
Chris

**Comment by hitvery** [comment]
Thanks for your patient response! I also agree with you that recent version is always the most correct decision, but sometimes is not the easiest:) I would do some experiments on old Bazel version, and also try to transmit a new Bazel version in our organization.
After all, It is definitely a pain point that fast updating compile commands for a big c++ repo.

**Comment by cpsauer** [comment]
Sounds good. Good luck! Please let me know how it goes.
